-- ═══════════════════════════════════════════════════════════════════════
-- BitCadence Score v1 Durable Store Migration (September 2026)
-- Packet S01a: Dedicated tables for Score documents, runs, tasks,
-- events, outbox, grants, reviews, providers, health, recovery, and
-- conductor leases.
--
-- Org-scoped data plane. Not located in the product DB schema name.
-- Idempotent: safe to run more than once.
-- ═══════════════════════════════════════════════════════════════════════

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ── 1. score_documents ────────────────────────────────────────────────
-- Immutable or versioned score definitions identified by SHA-256 digest.
CREATE TABLE IF NOT EXISTS score_documents (
  org_id      TEXT NOT NULL DEFAULT 'default',
  score_id    TEXT NOT NULL,
  revision    INTEGER NOT NULL DEFAULT 1,
  digest      TEXT PRIMARY KEY,
  document    JSONB NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_score_documents_org_score
  ON score_documents (org_id, score_id, revision);

-- ── 2. score_runs ─────────────────────────────────────────────────────
-- Instantiated execution of a specific score digest under an authorized budget.
CREATE TABLE IF NOT EXISTS score_runs (
  run_id                  TEXT PRIMARY KEY,
  org_id                  TEXT NOT NULL DEFAULT 'default',
  digest                  TEXT NOT NULL,
  principal               TEXT NOT NULL,
  credential_hash         TEXT,
  grants                  JSONB NOT NULL DEFAULT '[]'::jsonb,
  authorized_budget_cents BIGINT NOT NULL DEFAULT 0,
  status                  TEXT NOT NULL DEFAULT 'pending',
  policy_snapshot         JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_score_runs_org_status
  ON score_runs (org_id, status);
CREATE INDEX IF NOT EXISTS idx_score_runs_digest
  ON score_runs (digest);

-- ── 3. score_tasks ────────────────────────────────────────────────────
-- Execution state per task attempt. Idempotency enforced by unique attempt.
CREATE TABLE IF NOT EXISTS score_tasks (
  id                  TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  org_id              TEXT NOT NULL DEFAULT 'default',
  run_id              TEXT NOT NULL,
  task_id             TEXT NOT NULL,
  status              TEXT NOT NULL DEFAULT 'pending',
  attempt             INTEGER NOT NULL DEFAULT 1,
  author_id           TEXT,
  author_provider     TEXT,
  token               TEXT,
  deadline            TIMESTAMPTZ,
  evidence            JSONB,
  checkpoint_approved BOOLEAN NOT NULL DEFAULT FALSE,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_score_tasks_attempt UNIQUE (org_id, run_id, task_id, attempt)
);

CREATE INDEX IF NOT EXISTS idx_score_tasks_run_task
  ON score_tasks (org_id, run_id, task_id);
CREATE INDEX IF NOT EXISTS idx_score_tasks_status
  ON score_tasks (status);

-- ── 4. score_events ───────────────────────────────────────────────────
-- Append-only event stream for score execution transitions.
-- IMMUTABLE: no UPDATE/DELETE grants in SQL comments; no update helper.
CREATE TABLE IF NOT EXISTS score_events (
  seq         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id      TEXT NOT NULL DEFAULT 'default',
  run_id      TEXT NOT NULL,
  kind        TEXT NOT NULL,
  task_id     TEXT,
  digest      TEXT,
  at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  actor       TEXT,
  payload     JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_score_events_run_seq
  ON score_events (run_id, seq);
CREATE INDEX IF NOT EXISTS idx_score_events_task
  ON score_events (run_id, task_id);

CREATE OR REPLACE FUNCTION score_events_block_mutation()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'score_events is append-only: % is not allowed', tg_op;
END;
$$;

DROP TRIGGER IF EXISTS trg_score_events_immutable ON score_events;
CREATE TRIGGER trg_score_events_immutable
  BEFORE UPDATE OR DELETE ON score_events
  FOR EACH ROW EXECUTE FUNCTION score_events_block_mutation();

-- ── 5. score_outbox ───────────────────────────────────────────────────
-- Transactional outbox bridging score transitions to gateway job dispatches.
CREATE TABLE IF NOT EXISTS score_outbox (
  id          TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  org_id      TEXT NOT NULL DEFAULT 'default',
  score_id    TEXT NOT NULL,
  run_id      TEXT NOT NULL,
  digest      TEXT NOT NULL,
  task_id     TEXT NOT NULL,
  attempt     INTEGER NOT NULL DEFAULT 1,
  phase       TEXT NOT NULL DEFAULT 'work',
  job_id      TEXT NOT NULL,
  payload     JSONB NOT NULL DEFAULT '{}'::jsonb,
  status      TEXT NOT NULL DEFAULT 'planned' CHECK (status IN ('planned', 'sending', 'submitted', 'reconciled')),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uq_score_outbox_dispatch UNIQUE (org_id, run_id, task_id, phase),
  CONSTRAINT uq_score_outbox_job UNIQUE (job_id)
);

CREATE INDEX IF NOT EXISTS idx_score_outbox_run_status
  ON score_outbox (run_id, task_id, status);
CREATE INDEX IF NOT EXISTS idx_score_outbox_pending
  ON score_outbox (status) WHERE status IN ('planned', 'sending');

-- ── 6. score_grants ───────────────────────────────────────────────────
-- Signed owner authorizations bound to score digest and resource scopes.
CREATE TABLE IF NOT EXISTS score_grants (
  digest          TEXT PRIMARY KEY,
  org_id          TEXT NOT NULL DEFAULT 'default',
  actions         JSONB NOT NULL DEFAULT '[]'::jsonb,
  resources       JSONB NOT NULL DEFAULT '[]'::jsonb,
  env             TEXT NOT NULL DEFAULT 'production',
  expires_at      TIMESTAMPTZ NOT NULL,
  human_principal TEXT NOT NULL,
  signature       TEXT NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_score_grants_org
  ON score_grants (org_id, expires_at);

-- ── 7. score_reviews ──────────────────────────────────────────────────
-- Independent reviewer verdict and evidence verification record.
CREATE TABLE IF NOT EXISTS score_reviews (
  id                      TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  org_id                  TEXT NOT NULL DEFAULT 'default',
  run_id                  TEXT NOT NULL,
  task_id                 TEXT NOT NULL,
  attempt                 INTEGER NOT NULL DEFAULT 1,
  reviewer_id             TEXT NOT NULL,
  reviewer_provider       TEXT NOT NULL,
  head                    TEXT NOT NULL,
  verdict                 TEXT NOT NULL,
  evidence_binding        JSONB NOT NULL DEFAULT '{}'::jsonb,
  contribution_exclusion  JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_score_reviews_attempt
  ON score_reviews (org_id, run_id, task_id, attempt);

-- ── 8. score_providers ────────────────────────────────────────────────
-- Catalog of model/agent providers with capabilities and independence classes.
CREATE TABLE IF NOT EXISTS score_providers (
  instance_id         TEXT PRIMARY KEY,
  org_id              TEXT NOT NULL DEFAULT 'default',
  role                TEXT NOT NULL,
  provider            TEXT NOT NULL,
  capabilities        JSONB NOT NULL DEFAULT '[]'::jsonb,
  independence_class  TEXT NOT NULL DEFAULT 'default',
  cost_weight         NUMERIC NOT NULL DEFAULT 1.0,
  quota_window        JSONB NOT NULL DEFAULT '{}'::jsonb,
  approved_digests    JSONB NOT NULL DEFAULT '[]'::jsonb,
  authority_scopes    JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_score_providers_role
  ON score_providers (org_id, role);

-- ── 9. score_provider_health ──────────────────────────────────────────
-- Provider operational health, rate-limit backoff, and failure recovery.
CREATE TABLE IF NOT EXISTS score_provider_health (
  instance_id TEXT PRIMARY KEY,
  org_id      TEXT NOT NULL DEFAULT 'default',
  class       TEXT NOT NULL,
  reset_at    TIMESTAMPTZ,
  last_error  TEXT,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_score_provider_health_class
  ON score_provider_health (class);

-- ── 10. score_recovery ────────────────────────────────────────────────
-- Tracking for uncertain side-effects requiring compensation or human inspection.
CREATE TABLE IF NOT EXISTS score_recovery (
  approval_or_attempt_id  TEXT PRIMARY KEY,
  org_id                  TEXT NOT NULL DEFAULT 'default',
  uncertain_effect        JSONB NOT NULL DEFAULT '{}'::jsonb,
  decision                TEXT NOT NULL DEFAULT 'pending' CHECK (decision IN ('pending', 'inspected', 'compensated')),
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_score_recovery_decision
  ON score_recovery (org_id, decision);

-- ── 11. conductor_leases ──────────────────────────────────────────────
-- Distributed leases for competing conductor ticks (distinct from worker job leases).
CREATE TABLE IF NOT EXISTS conductor_leases (
  id          TEXT PRIMARY KEY,
  incarnation TEXT NOT NULL,
  owner       TEXT NOT NULL,
  expires_at  TIMESTAMPTZ NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_conductor_leases_expires
  ON conductor_leases (expires_at);
